### PR TITLE
Added doctor rain ideia

### PR DESCRIPTION
**Pull request by rzanluchi**

### CODE REVIEW

**Comment by csarcom** [comment]
"Analisys on which api is more assertive"

Any thoughts on how we will do that?
Which information will we use to determinate if the weather forecast was assertive or not? 1 day before? 2? same day?
Will we check assertivity looking one place?
Is there a way to automaticaly to do that? Or we will have to see the weather and check if the forecast was right?

**Comment by rzanluchi** [comment]
I don't know :)

**Comment by csarcom** [comment]
You could star it simple and we will see what happen...

Can you code that in ruby, c#, elixir...?

**Comment by rzanluchi** [comment]
That is the main point, I created a MVP description (very poor) and some advanced features. So after the MVP is ready if we want to we can start to think about the features

**Comment by mauricioabreu** [comment]
I liked the idea. Also the name of the project is very good :)
I came from a family who are farmers. They have some soy plantations and they could take advantage of an app like this (maybe having profiles to better inform users).

**Comment by rzanluchi** [comment]
My father in law's brother have soy plantations too. 

Maybe we can create more apps for stuff like that

**Comment by mauricioabreu** [comment]
Good. We can build the MVP and work on improvements later like you said.

**Comment by rzanluchi** [comment]
ok, merging this

**Pull request merged**
