### PR TITLE
Add Spotify Party idea

### PR DESCRIPTION
**Pull request by gtonello**

### CODE REVIEW

**Comment by gtonello** [comment]
How about this idea guys?!

**Comment by csarcom** [comment]
I did not understand...
Could you explain a little more?

**Comment by gtonello** [comment]
Oh God.. :-)
OK, Charles, you're on SM, and maybe you like to try a party.
But you don't know if exist parties on the summer in SM.
Open the App and it'll suggest parties, where you are, that play songs based on your style (from Spotify).
If you usually listen e-music, this kind of parties will be the 1st options that will be suggested.
And how we'll know about parties?! From flybynight.com, qualeaboa.com.br, etc.

**Comment by csarcom** [comment]
That is a useful explanation hahaha. I liked this idea.

:facepunch:

**Comment by mauricioabreu** [comment]
Pure inovation here. I don't think it already exists (what is good in some way). If this information is public we can do this of course.

**Comment by rzanluchi** [comment]
is like a social network ? with people filling the parties' information?

**Comment by mauricioabreu** [comment]
@rzanluchi @csarcom I don't think so.
I think @gtonello is thinking in an app that "connects" Spotify API to other APIs/informations.
On this app you enter your Spotify user, it relates your favourite musics to parties happening around you. Imagine that you like electronic music and there is a little party happening in Porto Alegre with this kind of music playing through all the night.

**Comment by gtonello** [comment]
Perfect, you got the idea @mauricioabreu.
The information abou parties/events we can find on the websites that I mentioned before.
But, you know, App is more complicate to do. Anyway.

**Comment by csarcom** [comment]
:+1:

**Comment by rzanluchi** [comment]
looks good :+1:

**Comment by rzanluchi** [comment]
@gtonello, could you please create a repo with this ideia?

**Pull request merged**
